# CLASS 1 NUMPY

In [1]:
a =[1,2,3,4,5,6,7,8,9,10]

In [2]:
a*5                      #SIMPLE MULTIPLICATION OF LIST  

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [3]:
d=[]
for c in a:
    d.append(c*5)
    
d                 #array does'nt need loop for this type of oprations

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [4]:
%time import numpy as np

Wall time: 258 ms


In [5]:
b=np.array(a)                   
b*5                  #ARRAY MULTIPLICATION   "simple"

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [6]:
numpyarray=np.array([22,33,44,55,66,77],dtype=np.int8)
print(type(numpyarray))
numpyarray

<class 'numpy.ndarray'>


array([22, 33, 44, 55, 66, 77], dtype=int8)

In [7]:
mylist = list(range(100000)) #initilizing list []

type(mylist) # cheacking type


list

In [8]:
empty = np.empty((5,5))
empty

array([[4.67296746e-307, 1.69121096e-306, 2.67023293e-307,
        1.89144350e-307, 5.78541272e-307],
       [6.23048521e-307, 8.45593934e-307, 7.56593017e-307,
        1.11261027e-306, 1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306, 7.56602523e-307],
       [1.29061821e-306, 1.60221072e-306, 8.34445138e-308,
        1.27946076e-307, 1.33511562e-306],
       [8.90103560e-307, 1.42410974e-306, 1.00132228e-307,
        1.33511969e-306, 2.18568966e-312]])

In [9]:
eye =np.eye(3)
eye                   #return diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
randomarray = np.random.randn(3)*100
randomarray

array([-62.7283657 , 159.2540149 , -60.78363162])

In [11]:
print(randomarray.ndim)
print(randomarray.shape)

1
(3,)


# ARRAY ------> VECTOR    '''you say  like 1 dimensional'''

# MATRIX -----> TENSOR    '''more then 1 dimension'''

In [12]:
twodimention = np.array([[1,2,3],[2,3,4],[4,5,6]])

print(twodimention)   

print("\n\n" + str(twodimention.ndim)) #dimension

print('\n\n'+str(twodimention.shape))  #shape

[[1 2 3]
 [2 3 4]
 [4 5 6]]


2


(3, 3)


In [13]:
zerodimension =np.array(100)
print(zerodimension.ndim)
print(zerodimension.shape)

0
()


In [14]:
miscD = np.array([[[[99]]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[[99]]]]
4
(1, 1, 1, 1)


In [15]:
miscD = np.array([[[[[[[99]]]]]]])          #[[[[[[[[[[[]]]]]]]]]]]   []most important
print(miscD)
print(miscD.ndim) 
print(miscD.shape)                      

[[[[[[[99]]]]]]]
7
(1, 1, 1, 1, 1, 1, 1)


In [16]:
af = np.arange(12).reshape(4,3)
af

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
af.ndim          #two dimension 

2

In [18]:
af>5                        # > symbol implement on more then one dimension array

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
af[af>5]

array([ 6,  7,  8,  9, 10, 11])

In [87]:
af != 5

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [88]:
af[af != 5]

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [89]:
af

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
af.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [91]:
af.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [96]:
af.sort()
af

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
flat = np.ravel(af) #ravel function convert any dimension to one dimension
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
flat.ndim

1

In [22]:
arr = np.arange(100000)   #initilizing array []
type(arr)  # cheacking type

numpy.ndarray

In [23]:
%time
for b in range(10):        #list multiplications' 
    listmuliti = mylist * 10

Wall time: 0 ns


In [24]:
%time
for b in range(11):
    arrmulti = arr * 2  #array multiplication

Wall time: 0 ns


In [25]:
data0 = np.arange(10) 
data0
#1 dementional vector array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
print(data0.ndim)        
print(data0.shape)        #shape is used to to check the array element distribution

1
(10,)


In [27]:
data1 =np.random.randn(5,3)
data1                      # two dimentional array (tensor)

array([[ 0.27812838, -0.17323369,  0.17253058],
       [-0.04497132,  0.3693314 ,  0.06161302],
       [-0.90582031,  0.59873003,  0.02615781],
       [ 0.39418692,  0.07085624, -0.04892916],
       [-1.22760681,  1.65213733,  1.06295201]])

In [28]:
print(data1.ndim)   #.ndim used for checking the array dimension
print(data1.shape)     #shape is used to to check the array element distribution

2
(5, 3)


In [29]:
data = np.random.randn(5, 3, 3)
data

array([[[ 1.7923403 , -0.54314895,  1.27496513],
        [ 0.1764707 , -0.79064545, -1.36127253],
        [-2.3345488 , -0.24209504,  0.44495708]],

       [[-0.64149517, -0.54643385,  0.02376147],
        [-0.50500024,  0.05062935, -0.26999303],
        [-0.58546936, -0.39489688,  0.40488703]],

       [[-1.69246666,  0.15304251, -0.34867905],
        [-0.88409401,  1.33150432, -0.81288635],
        [-1.48084413,  0.62823562, -1.97601227]],

       [[-1.18786232,  1.13134526,  0.96134345],
        [ 0.11309566,  0.36599064, -0.45373013],
        [ 2.69843604,  0.96360547, -0.11149955]],

       [[ 0.92657212,  2.03330081,  1.39664214],
        [-1.47519545, -0.70531643, -1.01724582],
        [-0.20702964, -1.24114464,  1.10231581]]])

In [30]:
print(data.ndim)
print(data.shape)

3
(5, 3, 3)


In [31]:
%time mylist[1:3] * 11           #check the time for multiplication

Wall time: 0 ns


[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [32]:
 %time data *10   #array multiplication check the time for multiplication 

Wall time: 0 ns


array([[[ 17.92340302,  -5.43148952,  12.7496513 ],
        [  1.76470699,  -7.90645452, -13.61272534],
        [-23.345488  ,  -2.4209504 ,   4.44957084]],

       [[ -6.41495169,  -5.46433848,   0.23761466],
        [ -5.05000242,   0.50629352,  -2.69993029],
        [ -5.85469362,  -3.94896882,   4.04887027]],

       [[-16.92466663,   1.53042509,  -3.4867905 ],
        [ -8.84094007,  13.31504316,  -8.12886353],
        [-14.80844127,   6.28235617, -19.76012273]],

       [[-11.87862325,  11.31345256,   9.61343452],
        [  1.13095664,   3.65990644,  -4.53730128],
        [ 26.98436045,   9.63605467,  -1.11499546]],

       [[  9.26572124,  20.33300809,  13.96642141],
        [-14.75195447,  -7.05316432, -10.17245822],
        [ -2.07029643, -12.41144639,  11.02315811]]])

In [33]:
datat1 = np.random.randn(2, 3, 3)
datat2 =np.random.randn(2,3,3)

In [34]:
datat1 - datat2   ########subtraction

array([[[-1.10533995, -0.3160635 ,  0.7320234 ],
        [-1.73167534, -0.85061549,  2.19949507],
        [-3.13743594,  1.33400774, -0.57897231]],

       [[ 0.51261911,  2.08012209,  0.8339253 ],
        [-0.19944559,  1.82935825,  0.77265924],
        [ 0.79910725, -1.14847604, -1.66768191]]])

In [35]:
datat1 + datat2  #addtion

array([[[ 1.6615877 ,  0.01825231, -2.67665718],
        [-0.18866365,  0.76224282, -0.57173398],
        [ 1.00476234,  1.41614167,  2.03083582]],

       [[ 0.11017955,  0.37382644, -1.23708699],
        [-1.24126656, -2.20089321, -0.56560994],
        [-0.42632065, -0.38482838, -2.30513351]]])

In [36]:
datat2 * datat1 ##multiplication                    ##broadcasting

array([[[ 0.38477432, -0.02489075,  1.65715886],
        [-0.74077638, -0.03563315, -1.12772471],
        [-2.20848923,  0.05647014,  0.9472713 ]],

       [[-0.0626597 , -1.04679043,  0.2087382 ],
        [ 0.37524103,  0.37434483, -0.06927192],
        [-0.11420577, -0.29272608,  0.63311938]]])

In [37]:
datat1 / datat2   #division

array([[[ 0.20103444, -0.89080796,  0.57049458],
        [-1.24453949, -0.05479258, -0.58737876],
        [-0.51486516, 33.48371883,  0.55631044]],

       [[-1.54755825, -1.43817312,  0.1946689 ],
        [ 1.38287881,  0.09218655, -0.15471424],
        [-0.30420933, -2.00786895,  6.23234054]]])

In [38]:
%time datat1 @ datat2  #matric multiplication

Wall time: 2 ms


array([[[-1.7438719 , -0.11352131, -1.53647224],
        [ 0.32317752, -0.16270947,  2.75971681],
        [ 1.08911643,  0.96046552,  0.85934858]],

       [[-0.57829207, -2.81514545, -1.07921783],
        [ 0.17828712,  1.02844322,  0.83724061],
        [ 1.57895087,  0.62742176,  0.95310149]]])

In [39]:
%time np.dot(datat1,datat2) #matric multiplication (numpy function )  

Wall time: 0 ns


array([[[[-1.7438719 , -0.11352131, -1.53647224],
         [ 0.61735459, -0.30847104,  0.12154138]],

        [[ 0.32317752, -0.16270947,  2.75971681],
         [-0.28245375,  1.21896652,  0.76442329]],

        [[ 1.08911643,  0.96046552,  0.85934858],
         [-0.94651129, -1.58402747, -0.04728492]]],


       [[[ 0.95993362,  1.03324236, -2.49388745],
         [-0.57829207, -2.81514545, -1.07921783]],

        [[-0.92549746, -0.26597008,  1.62022373],
         [ 0.17828712,  1.02844322,  0.83724061]],

        [[-4.44765559, -0.66866931, -1.84746467],
         [ 1.57895087,  0.62742176,  0.95310149]]]])

In [40]:
%time data1.dot(datat2)

Wall time: 0 ns


array([[[ 0.60845769, -0.08612404, -0.00885442],
        [-0.07143758,  0.17767934, -0.22707694]],

       [[ 0.35033181,  0.29285256, -0.35470545],
        [-0.22109063, -0.68235671, -0.220202  ]],

       [[-0.73707051,  0.33249255,  0.74835045],
        [-0.14564304, -0.42372999,  0.52901436]],

       [[ 0.49867221,  0.12102262, -0.83385593],
        [-0.08624838, -0.49776625, -0.44000035]],

       [[ 1.777763  ,  1.17077974,  1.19008465],
        [-1.26488241, -1.87607397, -0.17309807]]])

In [41]:
np.zeros(100).reshape(10,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.empty((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
print(datat1.shape)
print(datat1.dtype) #dtype is used for data type cheacking

(2, 3, 3)
float64


In [46]:
np.ones((2,3),dtype='uint8')#CHANge of datatype unsigned integar  press shift+tab to check the default parameter

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [47]:
np.ones((4,8),)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
datat1

array([[[ 0.27812387, -0.14890559, -0.97231689],
        [-0.9601695 , -0.04418633,  0.81388054],
        [-1.0663368 ,  1.37507471,  0.72593176]],

       [[ 0.31139933,  1.22697427, -0.20158084],
        [-0.72035607, -0.18576748,  0.10352465],
        [ 0.1863933 , -0.76665221, -1.98640771]]])

In [50]:
np.ones_like(datat1) #the entire datat1 change into the ones format

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [51]:
np.full((4,2),5) #used to make arry of desired value


array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [52]:
np.full_like(datat1,3,dtype='int64')

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]], dtype=int64)

In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arrt1 = np.array([1,2,3],)
arrt1

array([1, 2, 3])

In [55]:
arrt2 = np.array([1,2,3],dtype='float32')
arrt2

array([1., 2., 3.], dtype=float32)

In [56]:
arrt2.dtype

dtype('float32')

In [57]:
arrt2.astype(np.int) #change of data type

array([1, 2, 3])

In [58]:
arrnumeric = np.array(['21','1','54.6','-675.5'],dtype=np.string_)

In [59]:
arrnumeric.astype(np.float)

array([  21. ,    1. ,   54.6, -675.5])

In [60]:
a=[1.1,2,'a']

In [61]:
type(a[0])

float

In [62]:
type(a[1])

int

In [63]:
type(a[2])

str

In [64]:
a[0:2]

[1.1, 2]

In [65]:
atg = np.array([[[[1]]]])

In [66]:
atg.ndim

4

In [67]:
atg.shape

(1, 1, 1, 1)

In [68]:
type(atg)

numpy.ndarray

In [69]:
atg1 = np.arange(10).reshape(5,2)
atg1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [70]:
atg1[2][0]

4

In [71]:
atg1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Basic Indexing and Slicing

In [83]:
l=[1,2,3,4,5,5]
l

[1, 2, 3, 4, 5, 5]

In [84]:
l[6:]

[]

In [86]:
l[6] ################## so i think slicing and indexing concept is clear

IndexError: list index out of range

In [72]:
aList = [99,77,55,33,11]

In [73]:
type(aList[0:3])

list

In [74]:
tDarray  = np.arange(36).reshape(6,6)
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [75]:
ah= tDarray.astype("float64")
ah

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [76]:
tDarray[3,2]

20

In [77]:
tDarray[3][2]

20

In [78]:
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# tDarray[row,column]

# tDarray[start:end, start:end]

In [79]:
tDarray[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [80]:
tDarray[5:,3:4]

array([[33]])

In [81]:
tDarray[1:2,2:5]

array([[ 8,  9, 10]])

In [82]:
atg1[2:,0:]

array([[4, 5],
       [6, 7],
       [8, 9]])

# END OF CLASS 1 NUMPY

"ATG"