# CLASS 1 NUMPY

In [1]:
a =[1,2,3,4,5,6,7,8,9,10]

In [2]:
a*5                      #SIMPLE MULTIPLICATION OF LIST  

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [3]:
d=[]
for c in a:
    d.append(c*5)
    
d                 #array does'nt need loop for this type of oprations

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [4]:
%time import numpy as np

Wall time: 2.6 s


In [5]:
b=np.array(a)                   
b*5                  #ARRAY MULTIPLICATION   "simple"

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [6]:
numpyarray=np.array([22,33,44,55,66,77],dtype=np.int8)
print(type(numpyarray))
numpyarray

<class 'numpy.ndarray'>


array([22, 33, 44, 55, 66, 77], dtype=int8)

In [7]:
mylist = list(range(100000)) #initilizing list []

type(mylist) # cheacking type


list

In [8]:
randomarray = np.random.randn(3)*100
randomarray

array([4.92680688e-02, 1.09674876e+02, 1.08934947e+02])

In [9]:
print(randomarray.ndim)
print(randomarray.shape)

1
(3,)


# ARRAY ------> VECTOR    '''you say  like 1 dimensional'''

# MATRIX -----> TENSOR    '''more then 1 dimension'''

In [10]:
twodimention = np.array([[1,2,3],[2,3,4],[4,5,6]])

print(twodimention)   

print("\n\n" + str(twodimention.ndim)) #dimension

print('\n\n'+str(twodimention.shape))  #shape

[[1 2 3]
 [2 3 4]
 [4 5 6]]


2


(3, 3)


In [11]:
zerodimension =np.array(100)
print(zerodimension.ndim)
print(zerodimension.shape)

0
()


In [12]:
miscD = np.array([[[[99]]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[[99]]]]
4
(1, 1, 1, 1)


In [13]:
miscD = np.array([[[[[[[99]]]]]]])          #[[[[[[[[[[[]]]]]]]]]]]   []most important
print(miscD)
print(miscD.ndim) 
print(miscD.shape)                      

[[[[[[[99]]]]]]]
7
(1, 1, 1, 1, 1, 1, 1)


In [14]:
af = np.arange(12).reshape(4,3)
af

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
af.ndim          #two dimension 

2

In [16]:
flat = np.ravel(af) #ravel function convert any dimension to one dimension
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
flat.ndim

1

In [18]:
arr = np.arange(100000)   #initilizing array []
type(arr)  # cheacking type

numpy.ndarray

In [19]:
%time
for b in range(10):        #list multiplications' 
    listmuliti = mylist * 10

Wall time: 0 ns


In [20]:
%time
for b in range(11):
    arrmulti = arr * 2  #array multiplication

Wall time: 0 ns


In [21]:
data0 = np.arange(10) 
data0
#1 dementional vector array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
print(data0.ndim)        
print(data0.shape)        #shape is used to to check the array element distribution

1
(10,)


In [23]:
data1 =np.random.randn(5,3)
data1                      # two dimentional array (tensor)

array([[ 0.24745242, -1.07846579, -0.24936386],
       [-0.41516055,  1.04301505, -0.56859243],
       [-0.31818849,  1.77104764,  0.86086911],
       [ 0.45584136,  0.51168565,  0.73517167],
       [ 0.6931705 , -0.5455579 , -2.19269069]])

In [24]:
print(data1.ndim)   #.ndim used for checking the array dimension
print(data1.shape)     #shape is used to to check the array element distribution

2
(5, 3)


In [25]:
data = np.random.randn(5, 3, 3)
data

array([[[-0.05786289,  0.66455265,  0.41549377],
        [-0.75172296,  1.90265916,  0.09577219],
        [ 0.67666973,  0.5856018 ,  0.38736981]],

       [[-0.1179698 , -0.87451354, -0.61050963],
        [-1.05580929,  0.74139686,  0.22743537],
        [ 0.79962777, -0.96730352,  0.9146017 ]],

       [[ 0.43430109,  1.40217512, -0.28418624],
        [-1.67842246,  0.89660447,  0.39910995],
        [-0.76190589, -0.68975813,  1.66374498]],

       [[ 0.82366932, -0.66009218, -0.32279068],
        [-0.03875929,  1.75027106, -2.67501332],
        [-1.04164471,  0.87149479, -1.31042373]],

       [[ 0.62925325, -0.17910639,  0.31230296],
        [-0.09682223,  0.12568907, -1.97156185],
        [ 0.01806286, -0.27248071, -1.22848888]]])

In [26]:
print(data.ndim)
print(data.shape)

3
(5, 3, 3)


In [27]:
%time mylist[1:3] * 11           #check the time for multiplication

Wall time: 0 ns


[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [28]:
 %time data *10   #array multiplication check the time for multiplication 

Wall time: 0 ns


array([[[ -0.57862886,   6.64552651,   4.1549377 ],
        [ -7.51722961,  19.02659156,   0.95772194],
        [  6.76669733,   5.85601801,   3.8736981 ]],

       [[ -1.179698  ,  -8.74513543,  -6.10509628],
        [-10.55809286,   7.41396863,   2.27435369],
        [  7.99627772,  -9.67303516,   9.14601696]],

       [[  4.34301093,  14.02175118,  -2.84186243],
        [-16.78422461,   8.96604467,   3.9910995 ],
        [ -7.61905887,  -6.89758126,  16.6374498 ]],

       [[  8.23669315,  -6.60092181,  -3.22790682],
        [ -0.3875929 ,  17.50271062, -26.75013323],
        [-10.41644711,   8.71494789, -13.10423726]],

       [[  6.29253251,  -1.79106393,   3.12302964],
        [ -0.96822234,   1.25689071, -19.7156185 ],
        [  0.18062857,  -2.72480713, -12.28488878]]])

In [29]:
datat1 = np.random.randn(2, 3, 3)
datat2 =np.random.randn(2,3,3)

In [30]:
datat1 - datat2   ########subtraction

array([[[ 1.23412461, -0.63141104,  0.47388147],
        [ 0.43277025, -3.26069089, -0.38467353],
        [-2.3458389 , -0.45906783, -0.00354249]],

       [[ 0.52172212, -1.55035104, -0.23441607],
        [ 1.11940354,  1.10174281, -0.83655581],
        [-0.65351123,  0.13156149, -3.25875422]]])

In [31]:
datat1 + datat2  #addtion

array([[[-0.27401924, -3.16831114, -2.3973212 ],
        [ 1.84628072, -1.09937694,  1.26345924],
        [ 2.2835459 ,  0.28807631, -1.79091375]],

       [[ 0.30039298, -1.38006994,  0.43585457],
        [ 0.11745072, -0.10361931, -1.65933909],
        [ 0.1577293 , -0.52063954,  0.21357232]]])

In [32]:
datat2 * datat1 ##multiplication                    ##broadcasting

array([[[-0.36199425,  2.40987889,  1.38064632],
        [ 0.8053656 , -2.35586885,  0.36208888],
        [-0.07209457, -0.03193883,  0.80183988]],

       [[-0.04548951, -0.12474883,  0.03375458],
        [-0.30981741, -0.30077506,  0.51339515],
        [-0.1005496 ,  0.06343928, -2.64346648]]])

In [33]:
datat1 / datat2   #division

array([[[-6.36613915e-01,  1.49778155e+00,  6.69907336e-01],
        [ 1.61233399e+00, -2.01732276e+00,  5.33200797e-01],
        [-1.34560002e-02, -2.28860143e-01,  1.00396392e+00]],

       [[-3.71444568e+00, -1.72093144e+01,  3.00533084e-01],
        [-1.23444362e+00, -8.28069402e-01,  3.03347791e+00],
        [-6.11140480e-01,  5.96561548e-01, -8.76986042e-01]]])

In [34]:
%time datat1 @ datat2  #matric multiplication

Wall time: 248 ms


array([[[-3.93081667, -3.02129267, -1.39530071],
        [-1.38297525, -3.63715512, -3.82507607],
        [-2.11374499, -0.38806318,  0.77609966]],

       [[ 0.72940015,  0.88520768,  0.91540032],
        [-0.82464891,  0.15883447, -2.16469358],
        [-0.49270153,  0.59265711, -2.64651177]]])

In [35]:
%time np.dot(datat1,datat2) #matric multiplication (numpy function )  

Wall time: 96.1 ms


array([[[[-3.93081667, -3.02129267, -1.39530071],
         [ 0.5085677 ,  1.49949959, -0.72723312]],

        [[-1.38297525, -3.63715512, -3.82507607],
         [ 1.14426711,  1.26759874,  2.0416007 ]],

        [[-2.11374499, -0.38806318,  0.77609966],
         [-0.31765574,  0.3414614 , -1.53300057]]],


       [[[-1.11237806, -2.06717001, -1.88755683],
         [ 0.72940015,  0.88520768,  0.91540032]],

        [[-3.00223852, -0.71132769,  0.6387179 ],
         [-0.82464891,  0.15883447, -2.16469358]],

        [[-3.47489356, -0.46459011,  1.55627718],
         [-0.49270153,  0.59265711, -2.64651177]]]])

In [36]:
%time data1.dot(datat2)

Wall time: 0 ns


array([[[-1.5260089 , -1.57248799, -1.02111754],
        [ 0.41175467,  0.75235683,  0.09366548]],

       [[-0.26589931,  1.44134166,  1.96366157],
        [-0.70721498, -0.47853413, -1.55539192]],

       [[ 3.48428139,  2.63909786,  1.14690631],
        [-0.50285494, -1.37519747,  0.65937894]],

       [[ 1.71959561,  0.24938428, -0.88975587],
        [-0.0085874 , -0.50931253,  1.21864339]],

       [[-5.98368079, -2.28794111,  0.51488374],
        [-0.69279756,  1.1028519 , -3.35012516]]])

In [37]:
np.zeros(100).reshape(10,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
np.empty((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
print(datat1.shape)
print(datat1.dtype) #dtype is used for data type cheacking

(2, 3, 3)
float64


In [42]:
np.ones((2,3),dtype='uint8')#CHANge of datatype unsigned integar  press shift+tab to check the default parameter

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [43]:
np.ones((4,8),)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [44]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
datat1

array([[[ 0.48005268, -1.89986109, -0.96171986],
        [ 1.13952549, -2.18003391,  0.43939286],
        [-0.0311465 , -0.08549576, -0.89722812]],

       [[ 0.41105755, -1.46521049,  0.10071925],
        [ 0.61842713,  0.49906175, -1.24794745],
        [-0.24789096, -0.19453903, -1.52259095]]])

In [46]:
np.ones_like(datat1) #the entire datat1 change into the ones format

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
np.full((4,2),5) #used to make arry of desired value


array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [48]:
np.full_like(datat1,3,dtype='int64')

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]], dtype=int64)

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arrt1 = np.array([1,2,3],)
arrt1

array([1, 2, 3])

In [51]:
arrt2 = np.array([1,2,3],dtype='float32')
arrt2

array([1., 2., 3.], dtype=float32)

In [52]:
arrt2.dtype

dtype('float32')

In [53]:
arrt2.astype(np.int) #change of data type

array([1, 2, 3])

In [54]:
arrnumeric = np.array(['21','1','54.6','-675.5'],dtype=np.string_)

In [55]:
arrnumeric.astype(np.float)

array([  21. ,    1. ,   54.6, -675.5])

In [56]:
a=[1.1,2,'a']

In [57]:
type(a[0])

float

In [58]:
type(a[1])

int

In [59]:
type(a[2])

str

In [60]:
a[0:2]

[1.1, 2]

In [61]:
atg = np.array([[[[1]]]])

In [62]:
atg.ndim

4

In [63]:
atg.shape

(1, 1, 1, 1)

In [64]:
type(atg)

numpy.ndarray

In [65]:
atg1 = np.arange(10).reshape(5,2)
atg1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [66]:
atg1[2][0]

4

In [67]:
atg1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Basic Indexing and Slicing

In [68]:
aList = [99,77,55,33,11]

In [69]:
type(aList[0:3])

list

In [70]:
tDarray  = np.arange(36).reshape(6,6)
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [71]:
tDarray[3,2]

20

In [72]:
tDarray[3][2]

20

In [73]:
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# tDarray[row,column]

# tDarray[start:end, start:end]

In [74]:
tDarray[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [75]:
tDarray[5:,3:4]

array([[33]])

In [76]:
tDarray[1:2,2:5]

array([[ 8,  9, 10]])

In [77]:
atg1[2:,0:]

array([[4, 5],
       [6, 7],
       [8, 9]])

# END OF CLASS 1 NUMPY

"ATG"