# CLASS 1 NUMPY

In [3]:
%time import numpy as np

Wall time: 6.94 s


In [4]:
mylist = list(range(100000)) #initilizing list []

type(mylist) # cheacking type


list

In [5]:
arr = np.arange(100000)   #initilizing array []

type(arr)  # cheacking type

numpy.ndarray

In [6]:
%time
for b in range(10):        #list multiplications' 
    listmuliti = mylist * 10

Wall time: 0 ns


In [7]:
%time
for b in range(11):
    arrmulti = arr * 2  #array multiplication

Wall time: 0 ns


In [8]:
data0 = np.arange(10) 
data0
#1 dementional vector array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(data0.ndim)        
print(data0.shape)        #shape is used to to check the array element distribution

1
(10,)


In [10]:
data1 =np.random.randn(5,3)
data1                      # two dimentional array (tensor)

array([[ 0.44347956, -1.10827909,  0.50959615],
       [-2.00884697,  0.82366752, -0.63974336],
       [-0.58679592, -0.14809644, -0.15191394],
       [ 0.22070792,  1.72073308,  1.83287185],
       [-0.59838179,  0.44798382,  0.609792  ]])

In [11]:
print(data1.ndim)   #.ndim used for checking the array dimension
print(data1.shape)     #shape is used to to check the array element distribution

2
(5, 3)


In [12]:
data = np.random.randn(5, 3, 3)
data

array([[[-1.96491252,  1.71213396,  0.61239936],
        [ 0.55832522,  0.7306783 ,  0.41656201],
        [ 1.11513149,  2.04261019,  1.45646938]],

       [[ 2.5133733 , -0.88466276, -0.07796049],
        [ 1.12611959, -0.13487329,  0.79268379],
        [ 1.15553841, -0.11811718,  0.99938892]],

       [[ 0.97998959,  1.52954808,  0.17581348],
        [ 0.62235747,  0.29972008, -2.32250601],
        [-0.40507648,  0.109771  ,  0.08596048]],

       [[-0.70485432,  0.15538265, -0.7562316 ],
        [-2.46183349, -0.04676015, -1.31505021],
        [ 0.30828572,  0.20150876,  1.67039076]],

       [[ 1.16130832,  0.79836502, -1.04813333],
        [ 0.54985584, -0.37747208,  0.29343837],
        [-1.61561436,  1.50761954,  0.56204993]]])

In [13]:
print(data.ndim)
print(data.shape)

3
(5, 3, 3)


In [14]:
%time mylist[1:3] * 11           #check the time for multiplication

Wall time: 0 ns


[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [15]:
 %time data *10   #array multiplication check the time for multiplication 

Wall time: 0 ns


array([[[-19.64912521,  17.12133957,   6.12399362],
        [  5.58325222,   7.30678303,   4.16562005],
        [ 11.15131488,  20.42610189,  14.56469375]],

       [[ 25.13373305,  -8.84662758,  -0.77960494],
        [ 11.26119586,  -1.3487329 ,   7.9268379 ],
        [ 11.55538412,  -1.18117177,   9.99388925]],

       [[  9.79989587,  15.29548076,   1.75813476],
        [  6.22357473,   2.99720082, -23.2250601 ],
        [ -4.05076481,   1.09771003,   0.85960483]],

       [[ -7.04854321,   1.55382651,  -7.56231604],
        [-24.61833489,  -0.46760151, -13.15050215],
        [  3.08285716,   2.01508756,  16.70390755]],

       [[ 11.61308323,   7.98365024, -10.48133332],
        [  5.49855838,  -3.77472081,   2.9343837 ],
        [-16.15614364,  15.07619544,   5.62049932]]])

In [16]:
datat1 = np.random.randn(2, 3, 3)
datat2 =np.random.randn(2,3,3)

In [17]:
datat1 - datat2   ########subtraction

array([[[-3.20502143, -0.14609625,  0.8682342 ],
        [-0.37822731, -0.4376098 , -0.85071143],
        [-2.03676644,  0.86349811, -0.27686941]],

       [[-1.13378178,  0.14058504,  2.92245846],
        [ 1.90749732,  0.43969662, -1.45963585],
        [ 0.22672919, -0.83874436, -0.6767354 ]]])

In [18]:
datat1 + datat2  #addtion

array([[[-0.47088143,  0.48455095,  0.08196649],
        [-0.72752314, -0.33179829,  0.02779208],
        [-1.1675377 , -0.18492275,  1.89441453]],

       [[-2.43050128, -2.35763339,  0.49789484],
        [ 1.69571397, -0.49489313,  0.90472561],
        [-1.78482557,  3.32638707,  0.46196045]]])

In [19]:
datat2 * datat1 ##multiplication                    ##broadcasting

array([[[-2.51260826,  0.05336138, -0.18677803],
        [ 0.0965585 , -0.02035306, -0.18073438],
        [-0.69631831, -0.17785814,  0.87803743]],

       [[ 1.15546883,  1.38466777, -2.07321605],
        [-0.19077504,  0.01289652, -0.3280021 ],
        [ 0.78354904,  2.59033972, -0.06114084]]])

In [20]:
datat1 / datat2   #division

array([[[ -1.34444574,   0.53667835,  -1.20849513],
        [  3.16565608,  -7.27149691,  -0.93672858],
        [ -3.68637621,  -0.64723565,   0.74497171]],

       [[  2.74869243,   0.88745176,  -1.41070883],
        [-17.01366632,   0.05905961,  -0.23469772],
        [  0.77457318,   0.59725432,  -0.18861486]]])

In [21]:
%time datat1 @ datat2  #matric multiplication

Wall time: 239 ms


array([[[-2.33567803, -0.81964892,  1.31268322],
        [-0.86745766,  0.02100379, -0.39832585],
        [-1.89800574, -0.9112131 ,  1.65693036]],

       [[-0.44720467,  6.30565234,  1.82366737],
        [-0.88610807, -2.81532421, -2.37464837],
        [ 0.48140105,  0.16824345,  2.35370675]]])

In [22]:
%time np.dot(datat1,datat2) #matric multiplication (numpy function )  

Wall time: 62 ms


array([[[[-2.33567803, -0.81964892,  1.31268322],
         [ 0.69588878,  3.2061507 ,  2.6986698 ]],

        [[-0.86745766,  0.02100379, -0.39832585],
         [ 0.81303583,  0.01347996, -0.01881283]],

        [[-1.89800574, -0.9112131 ,  1.65693036],
         [ 0.18939803,  3.52703753,  2.80383214]]],


       [[[-1.49944344, -1.51709103,  2.07033852],
         [-0.44720467,  6.30565234,  1.82366737]],

        [[ 2.34715502,  0.71207354, -1.02161167],
         [-0.88610807, -2.81532421, -2.37464837]],

        [[-1.32891635, -0.12355333,  0.73603658],
         [ 0.48140105,  0.16824345,  2.35370675]]]])

In [23]:
%time data1.dot(datat2)

Wall time: 0 ns


array([[[ 1.02130405e+00, -1.85930390e-01, -1.07921395e-01],
        [-6.82717051e-01,  1.02520620e+00, -1.55767088e+00]],

       [[-3.16812790e+00, -2.54499964e-01,  4.57010918e-01],
        [ 1.85867538e+00,  7.92066080e-01,  3.04477596e+00]],

       [[-8.42350345e-01, -1.13230885e-01,  7.13574140e-04],
        [ 5.48928638e-01,  4.85806142e-01,  4.49793380e-01]],

       [[ 7.97793180e-01, -8.00179437e-01,  2.65890987e+00],
        [-2.16877048e+00,  2.73729802e+00,  2.81019906e+00]],

       [[-6.31244861e-01, -4.84642303e-01,  1.09403761e+00],
        [-2.72786095e-01,  1.80803558e+00,  1.60218901e+00]]])

In [24]:
np.zeros(100).reshape(10,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.empty((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
print(datat1.shape)
print(datat1.dtype) #dtype is used for data type cheacking

(2, 3, 3)
float64


In [29]:
np.ones((2,3),dtype='uint8')#CHANge of datatype unsigned integar  press shift+tab to check the default parameter

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [30]:
np.ones((4,8),)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
datat1

array([[[-1.83795143,  0.16922735,  0.47510035],
        [-0.55287523, -0.38470404, -0.41145967],
        [-1.60215207,  0.33928768,  0.80877256]],

       [[-1.78214153, -1.10852418,  1.71017665],
        [ 1.80160564, -0.02759826, -0.27745512],
        [-0.77904819,  1.24382136, -0.10738748]]])

In [33]:
np.ones_like(datat1) #the entire datat1 change into the ones format

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
np.full((4,2),5) #used to make arry of desired value


array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [35]:
np.full_like(datat1,3,dtype='int64')

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]], dtype=int64)

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arrt1 = np.array([1,2,3],)
arrt1

array([1, 2, 3])

In [38]:
arrt2 = np.array([1,2,3],dtype='float32')
arrt2

array([1., 2., 3.], dtype=float32)

In [39]:
arrt2.dtype

dtype('float32')

In [40]:
arrt2.astype(np.int) #change of data type

array([1, 2, 3])

In [41]:
arrnumeric = np.array(['21','1','54.6','-675.5'],dtype=np.string_)

In [42]:
arrnumeric.astype(np.float)

array([  21. ,    1. ,   54.6, -675.5])

In [43]:
a=[1.1,2,'a']

In [44]:
type(a[0])

float

In [45]:
type(a[1])

int

In [46]:
type(a[2])

str

In [47]:
a[0:2]

[1.1, 2]

In [48]:
atg = np.array([[[[1]]]])

In [49]:
atg.ndim

4

In [50]:
atg.shape

(1, 1, 1, 1)

In [51]:
type(atg)

numpy.ndarray

In [52]:
atg1 = np.arange(10).reshape(5,2)
atg1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
atg1[2][0]

4

In [54]:
atg1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
atg1[2:,0:]

array([[4, 5],
       [6, 7],
       [8, 9]])

# END OF CLASS 1 NUMPY